Repository softeerbootcamp4th/Team1-Strawberry-FE, pull requests merged in 2024-07, with the labels that each got.

#2 프로젝트를 세팅합니다
  .github/PULL_REQUEST_TEMPLATE/template.md
  strawberry/.eslintrc.cjs
  strawberry/.gitignore
  strawberry/README.md
  strawberry/index.html
  strawberry/package-lock.json
  strawberry/package.json
  strawberry/public/vite.svg
  strawberry/src/App.css
  strawberry/src/App.tsx
  strawberry/src/assets/react.svg
  strawberry/src/index.css
  strawberry/src/main.tsx
  strawberry/src/modules/core/design_system/reset.css
  strawberry/src/modules/core/dummy copy.ts
  strawberry/src/modules/drawing_event/dummy copy 8.ts
  strawberry/src/modules/expectation/dummy copy 7.ts
  strawberry/src/modules/landing/dummy copy 6.ts
  strawberry/src/modules/login/dummy copy 3.ts
  strawberry/src/modules/new_car/dummy copy 2.ts
  strawberry/src/modules/quiz_event/dummy copy 4.ts
  strawberry/src/pages/dummy copy 5.ts
  strawberry/src/routers/dummy.ts
  strawberry/src/vite-env.d.ts
  strawberry/tsconfig.app.json
  strawberry/tsconfig.json
  strawberry/tsconfig.node.json
  strawberry/vite.config.ts
Labels: :bread: chore

#3 프로젝트를 세팅합니다(#1)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/template.md
  strawberry/.eslintrc.cjs
  strawberry/.gitignore
  strawberry/README.md
  strawberry/index.html
  strawberry/package-lock.json
  strawberry/package.json
  strawberry/public/vite.svg
  strawberry/src/App.css
  strawberry/src/App.tsx
  strawberry/src/assets/react.svg
  strawberry/src/index.css
  strawberry/src/main.tsx
  strawberry/src/modules/core/design_system/reset.css
  strawberry/src/modules/core/dummy copy.ts
  strawberry/src/modules/drawing_event/dummy copy 8.ts
  strawberry/src/modules/expectation/dummy copy 7.ts
  strawberry/src/modules/landing/dummy copy 6.ts
  strawberry/src/modules/login/dummy copy 3.ts
  strawberry/src/modules/new_car/dummy copy 2.ts
  strawberry/src/modules/quiz_event/dummy copy 4.ts
  strawberry/src/pages/dummy copy 5.ts
  strawberry/src/routers/dummy.ts
  strawberry/src/vite-env.d.ts
  strawberry/tsconfig.app.json
  strawberry/tsconfig.json
  strawberry/tsconfig.node.json
  strawberry/vite.config.ts
Labels: :bread: chore

#6 pr 템플릿을 등록합니다
  .github/pull_request_template.md
Labels: :baguette_bread: rename

#7 폰트, 컬러, 섀도우, 래디어스 디자인시스템을 개발합니다.
  strawberry/.gitignore
  strawberry/src/App.css
  strawberry/src/App.tsx
  strawberry/src/index.css
  strawberry/src/main.tsx
  strawberry/src/modules/core/design_system/border.tsx
  strawberry/src/modules/core/design_system/color.tsx
  strawberry/src/modules/core/design_system/reset.css
  strawberry/src/modules/core/design_system/shadow.tsx
  strawberry/src/modules/core/design_system/theme.tsx
  strawberry/src/modules/core/design_system/typography.tsx
Labels: :pretzel: feat

#10 리액트 라우터를 설치합니다.
  strawberry/package-lock.json
  strawberry/package.json
Labels: :bread: chore

#11 헤더를 구현하였습니다.
  strawberry/src/assets/images/logos/Hyundai_Motor_Company_logo_1.svg
  strawberry/src/modules/core/components/header/CarIntroButton.tsx
  strawberry/src/modules/core/components/header/Header.tsx
  strawberry/src/modules/core/components/header/HeaderLogo.tsx
  strawberry/src/modules/core/components/header/HeaderMenuButtons.tsx
  strawberry/src/modules/core/components/header/LoginButton.tsx
  strawberry/src/modules/core/components/header/LogoutButton.tsx
  strawberry/src/modules/core/components/header/index.ts
  strawberry/src/modules/core/design_system/styles/DefaultButton.tsx
Labels: :pretzel: feat

#14 푸터를 구현하였습니다.
  strawberry/src/assets/images/footer/tmp_footer.svg
  strawberry/src/modules/core/components/footer/Footer.tsx
  strawberry/src/modules/core/components/footer/index.ts
Labels: :pretzel: feat

#16 Global Context API를 추가합니다.
  strawberry/src/App.tsx
  strawberry/src/modules/core/contexts/globalContext.tsx
  strawberry/src/modules/core/hooks/useGlobalDispatch.tsx
  strawberry/src/modules/core/hooks/useGlobalState.tsx
Labels: :pretzel: feat

#17 레이아웃을 추가합니다.
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/layout/components/footer/Footer.tsx
  strawberry/src/layout/components/footer/index.ts
  strawberry/src/layout/components/header/CarIntroButton.tsx
  strawberry/src/layout/components/header/Header.tsx
  strawberry/src/layout/components/header/HeaderLogo.tsx
  strawberry/src/layout/components/header/HeaderMenuButtons.tsx
  strawberry/src/layout/components/header/LoginButton.tsx
  strawberry/src/layout/components/header/LogoutButton.tsx
  strawberry/src/layout/components/header/index.ts
Labels: :pretzel: feat

#19 폴더 구조를 변경합니다.
  strawberry/index.html
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/core/design_system/border.tsx
  strawberry/src/core/design_system/color.tsx
  strawberry/src/core/design_system/reset.css
  strawberry/src/core/design_system/shadow.tsx
  strawberry/src/core/design_system/styles/DefaultButton.tsx
  strawberry/src/core/design_system/theme.tsx
  strawberry/src/core/design_system/typography.tsx
  strawberry/src/core/hooks/useGlobalDispatch.tsx
  strawberry/src/core/hooks/useGlobalState.tsx
  strawberry/src/core/utils/dummy copy 5.ts
  strawberry/src/layout/components/header/CarIntroButton.tsx
  strawberry/src/layout/components/header/HeaderMenuButtons.tsx
  strawberry/src/layout/components/header/LoginButton.tsx
  strawberry/src/layout/components/header/LogoutButton.tsx
  strawberry/src/main.tsx
  strawberry/src/pages/common/components/dummy copy 5.ts
  strawberry/src/pages/common/contexts/dummy copy 5.ts
  strawberry/src/pages/common/hooks/dummy copy 5.ts
  strawberry/src/pages/common/services/dummy copy 5.ts
  strawberry/src/pages/drawing/components/dummy copy 5.ts
  strawberry/src/pages/drawing/contexts/dummy copy 5.ts
  strawberry/src/pages/drawing/hooks/dummy copy 5.ts
  strawberry/src/pages/drawing/services/dummy copy 5.ts
  strawberry/src/pages/expectation/components/dummy copy 5.ts
  strawberry/src/pages/expectation/contexts/dummy copy 5.ts
  strawberry/src/pages/expectation/hooks/dummy copy 5.ts
  strawberry/src/pages/expectation/services/dummy copy 5.ts
  strawberry/src/pages/introduce/components/dummy copy 5.ts
  strawberry/src/pages/introduce/contexts/dummy copy 5.ts
  strawberry/src/pages/introduce/hooks/dummy copy 5.ts
  strawberry/src/pages/introduce/services/dummy copy 5.ts
  strawberry/src/pages/login/components/dummy copy 5.ts
  strawberry/src/pages/login/contexts/dummy copy 5.ts
  strawberry/src/pages/login/hooks/dummy copy 5.ts
  strawberry/src/pages/login/services/dummy copy 5.ts
  strawberry/src/pages/newCar/components/dummy copy 5.ts
  strawberry/src/pages/newCar/contexts/dummy copy 5.ts
  strawberry/src/pages/newCar/hooks/dummy copy 5.ts
  strawberry/src/pages/newCar/services/dummy copy 5.ts
  strawberry/src/pages/quiz/components/dummy copy 5.ts
  strawberry/src/pages/quiz/contexts/dummy copy 5.ts
  strawberry/src/pages/quiz/hooks/dummy copy 5.ts
  strawberry/src/pages/quiz/services/dummy copy 5.ts
  strawberry/src/router/dummy.ts
Labels: :sandwich: refactor

#21 라우터 구조를 추가합니다.
  strawberry/src/App.tsx
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/router/ProtectedRoute.tsx
  strawberry/src/router/PublicRoute.tsx
  strawberry/src/router/dummy.ts
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#24 이벤트 버튼을 구현합니다.
  strawberry/src/assets/images/icons/Arrow_Right_L_Black.svg
  strawberry/src/assets/images/icons/Arrow_Right_L_White.svg
  strawberry/src/core/design_system/buttons/EventButton.tsx
  strawberry/src/core/design_system/color.tsx
  strawberry/src/core/design_system/reset.css
Labels: :pretzel: feat

#26 네트워크 Config를 구성하고 사용 예제를 만듭니다.
  strawberry/package-lock.json
  strawberry/package.json
  strawberry/public/user.json
  strawberry/src/App.tsx
  strawberry/src/data/config/customError.tsx
  strawberry/src/data/config/handleQueryError.tsx
  strawberry/src/data/config/logging.tsx
  strawberry/src/data/config/request.tsx
  strawberry/src/data/config/response.tsx
  strawberry/src/data/config/url.tsx
  strawberry/src/data/config/useFetch.tsx
  strawberry/src/data/example/user/useUserQuery.tsx
Labels: :pretzel: feat

#27 퀴즈 이벤트 페이지의 CardInput을 구현합니다.
  strawberry/src/core/design_system/color.tsx
  strawberry/src/pages/quiz/components/CardInput.tsx
  strawberry/src/pages/quiz/components/dummy copy 5.ts
Labels: :pretzel: feat

#30 라우터의 children을 outlet으로 변경합니다.
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
Labels: :pretzel: feat

#32 레이아웃의 각 영역 크기에 대한 css를 설정합니다.
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
Labels: :pretzel: feat

#36 디자인시스템에 Label, Line, Wrapper 컴포넌트를 추가합니다.
  strawberry/src/core/design_system/foundation/border.tsx
  strawberry/src/core/design_system/foundation/color.tsx
  strawberry/src/core/design_system/foundation/shadow.tsx
  strawberry/src/core/design_system/foundation/typography.tsx
  strawberry/src/core/design_system/index.ts
  strawberry/src/core/design_system/reset.css
  strawberry/src/core/design_system/styles/Label.tsx
  strawberry/src/core/design_system/styles/Line.tsx
  strawberry/src/core/design_system/styles/Wrapper.tsx
  strawberry/src/core/design_system/theme.tsx
Labels: :baguette_bread: rename, :pancakes: fix, :pretzel: feat

#38 퀴즈 배너를 만듭니다.
  strawberry/src/assets/images/temp/QuizBannerImg.svg
  strawberry/src/core/utils/convertSeconds.tsx
  strawberry/src/pages/quiz/QuizLandingPage.tsx
  strawberry/src/pages/quiz/components/quizBanner/QuizBanner.tsx
  strawberry/src/pages/quiz/components/quizBanner/QuizBannerContent.tsx
  strawberry/src/pages/quiz/components/quizBanner/QuizBannerTimer.tsx
  strawberry/src/pages/quiz/components/quizBanner/TimerSection.tsx
  strawberry/src/pages/quiz/components/quizBanner/index.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#39 모달의 레이아웃을 제작합니다.
  strawberry/src/assets/images/icons/coupon_coffee.svg
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/pages/common/components/buttons/ModalButton.tsx
  strawberry/src/pages/common/components/dummy copy 5.ts
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/components/modal/QuizRewardModal.tsx
Labels: :pretzel: feat

#42 레이아웃의 div를 새로 만든 Wrapper로 변경합니다.
  strawberry/src/core/design_system/styles/Wrapper.tsx
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
Labels: :pretzel: feat

#46 context를 사용하여 공통된 모달을 분리합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/core/hooks/useGlobalDispatch.tsx
  strawberry/src/core/hooks/useGlobalState.tsx
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/components/modal/QuizRewardModal.tsx
  strawberry/src/pages/common/components/modal/TwoButtonModal.tsx
Labels: :pretzel: feat
