Repository softeerbootcamp4th/Team1-Strawberry-FE, pull requests merged in 2024-08, with the labels that each got.

#53 로그인 페이지를 구현합니다.
  strawberry/.gitignore
  strawberry/src/assets/images/login/hyundaiLoginButton.svg
  strawberry/src/assets/images/login/naverLoginButton.svg
  strawberry/src/pages/login/LoginPage.tsx
  strawberry/src/pages/login/hooks/dummy copy 5.ts
  strawberry/src/pages/login/hooks/useLogin.tsx
  strawberry/src/router/PublicRoute.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#56 소셜 로그인을 구현합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/data/config/url.tsx
  strawberry/src/data/config/useFetch.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/pages/login/LoginRedirectPage.tsx
  strawberry/src/pages/login/hooks/useHandleLoginRedirect.tsx
  strawberry/src/pages/login/hooks/useLogin.tsx
  strawberry/src/pages/login/hooks/useLoginCallbackQuery.tsx
  strawberry/src/router/ProtectedRoute.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#61 기대평 페이지를 구현합니다.
  strawberry/src/assets/images/background/expectationBG.svg
  strawberry/src/assets/images/icons/Arrow_Left_L_Gray.svg
  strawberry/src/assets/images/icons/Arrow_Right_L_Gray.svg
  strawberry/src/pages/expectation/ExpectationPage.tsx
  strawberry/src/pages/expectation/components/ExpectationBanner.tsx
  strawberry/src/pages/expectation/components/ExpectationInput.tsx
  strawberry/src/pages/expectation/components/ExpectationList.tsx
  strawberry/src/pages/expectation/components/ExpectationTitle.tsx
  strawberry/src/pages/expectation/components/Pagination.tsx
  strawberry/src/pages/expectation/components/SubmitButton.tsx
  strawberry/src/pages/expectation/components/dummy copy 5.ts
  strawberry/src/pages/expectation/components/index.tsx
  strawberry/src/pages/expectation/contexts/dummy copy 5.ts
  strawberry/src/pages/expectation/contexts/useExpectationListQuery.tsx
  strawberry/src/pages/expectation/hooks/useLengthValidation.tsx
  strawberry/src/pages/expectation/hooks/usePagination.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#64 Quiz Landing API를 연동합니다.
  strawberry/src/core/utils/formatEventDateTime.tsx
  strawberry/src/core/utils/index.tsx
  strawberry/src/data/config/useFetch.tsx
  strawberry/src/pages/quizLanding/QuizLandingPage.tsx
  strawberry/src/pages/quizLanding/QuizLandingWrapper.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBannerContent.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBannerTimer.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/TimerSection.tsx
  strawberry/src/pages/quizLanding/components/quizInfo/QuizInfo.tsx
  strawberry/src/pages/quizLanding/components/quizNotice/QuizNotice.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizOpen.tsx
  strawberry/src/pages/quizLanding/components/quizReward/QuizReward.tsx
  strawberry/src/pages/quizLanding/components/quizReward/QuizRewardItem.tsx
  strawberry/src/pages/quizLanding/contexts/QuizLandingContext.tsx
  strawberry/src/pages/quizLanding/hooks/index.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizLandingData.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizLandingDispatch.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizLandingQuery.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizLandingState.tsx
  strawberry/src/pages/quizLanding/hooks/useTimeConversion.tsx
  strawberry/src/pages/quizLanding/models/PrizeInfo.tsx
  strawberry/src/pages/quizLanding/models/QuizLanding.tsx
  strawberry/src/pages/quizLanding/models/QuizLandingAction.tsx
  strawberry/src/pages/quizLanding/models/QuizLandingState.tsx
  strawberry/src/pages/quizLanding/models/Timer.tsx
  strawberry/src/pages/quizLanding/models/index.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#78 useNavigationBlocker를 구현합니다.
  strawberry/src/pages/common/hooks/dummy copy 5.ts
  strawberry/src/pages/common/hooks/useNavigationBlock.tsx
Labels: :pretzel: feat

#71 모달 요소들의 스타일을 변경합니다.
  strawberry/src/pages/common/components/buttons/ModalButton.tsx
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/components/modal/TwoButtonModal.tsx
Labels: :pretzel: feat

#80 기대평 페이지 API를 연동합니다.
  strawberry/src/pages/expectation/ExpectationPage.tsx
  strawberry/src/pages/expectation/ExpectationPageWrapper.tsx
  strawberry/src/pages/expectation/components/ExpectationBanner.tsx
  strawberry/src/pages/expectation/components/ExpectationInput.tsx
  strawberry/src/pages/expectation/components/ExpectationList.tsx
  strawberry/src/pages/expectation/components/ExpectationTitle.tsx
  strawberry/src/pages/expectation/components/Pagination.tsx
  strawberry/src/pages/expectation/contexts/expectationContext.tsx
  strawberry/src/pages/expectation/contexts/useExpectationListQuery.tsx
  strawberry/src/pages/expectation/hooks/apis/useExpectationListQuery.tsx
  strawberry/src/pages/expectation/hooks/apis/useExpectationMutation.tsx
  strawberry/src/pages/expectation/hooks/apis/useExpectationPageQuery.tsx
  strawberry/src/pages/expectation/hooks/dummy copy 5.ts
  strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationPage.tsx
  strawberry/src/pages/expectation/hooks/logics/usePagination.tsx
  strawberry/src/pages/expectation/hooks/useExpectationData.tsx
  strawberry/src/pages/expectation/hooks/useExpectationDispatch.tsx
  strawberry/src/pages/expectation/hooks/useExpectationState.tsx
  strawberry/src/pages/expectation/hooks/usePage.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#82 로그인 상태를 검사하고 이벤트 페이지로 넘어갑니다.
  strawberry/src/core/hooks/useCheckLogin.tsx
  strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
Labels: :pretzel: feat

#95 reset.css에 이미지 veritcal-align을 top으로 설정합니다.
  strawberry/src/core/design_system/reset.css
Labels: :pancakes: fix

#96 roughjs의 import를 위해 최상단 경로에 파일을 추가합니다.
  strawberry/src/declarations.d.ts
Labels: :bread: chore

#89 TwoButtonModal의 레이아웃을 수정합니다.
  strawberry/src/pages/common/components/modal/TwoButtonModal.tsx
Labels: :pretzel: feat

#88 드로잉 게임에 context를 적용해 단계를 추가하고, 드로잉 게임 결과 화면을 구현합니다.
  strawberry/src/assets/images/background/exteriorBG.svg
  strawberry/src/assets/images/background/exteriorBlurBG.svg
  strawberry/src/assets/images/background/exteriorLineBG.svg
  strawberry/src/assets/images/background/gifBG.gif
  strawberry/src/assets/images/background/interiorBG.svg
  strawberry/src/assets/images/background/interiorBlurBG.svg
  strawberry/src/assets/images/background/interiorLineBG.svg
  strawberry/src/assets/images/background/santafeBlurBG.svg
  strawberry/src/assets/images/icons/RetryButton.svg
  strawberry/src/assets/images/icons/UrlButton.svg
  strawberry/src/pages/drawingPlay/DrawingPlayPage.tsx
  strawberry/src/pages/drawingPlay/DrawingPlayWrapper.tsx
  strawberry/src/pages/drawingPlay/components/DrawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/components/DrawingFinish/DrawingInput.tsx
  strawberry/src/pages/drawingPlay/components/DrawingFinish/HighestScore.tsx
  strawberry/src/pages/drawingPlay/components/DrawingGame/DrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/components/DrawingGame/DrawingGame.tsx
  strawberry/src/pages/drawingPlay/components/DrawingOnboarding/DrawingOnboarding.tsx
  strawberry/src/pages/drawingPlay/components/DrawingResult/DrawingResult.tsx
  strawberry/src/pages/drawingPlay/components/DrawingResult/ImageResult.tsx
  strawberry/src/pages/drawingPlay/components/DrawingScore.tsx
  strawberry/src/pages/drawingPlay/components/DrawingStep.tsx
  strawberry/src/pages/drawingPlay/components/ProgressBar.tsx
  strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingOnboarding.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPlayDispatch.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPlayPage.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPlayState.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingResult.tsx
  strawberry/src/pages/drawingPlay/hooks/useProgressBar.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#86 QuizPlay페이지에 구현된 Popover를 적용합니다.
  strawberry/src/pages/quiz/components/quizBoard/QuizQuestion.tsx
Labels: :pretzel: feat

#104 Build가 되지 않는 오류를 수정합니다
  strawberry/package.json
Labels: :pancakes: fix

#101 로그아웃 시 reload 코드를 추가합니다.
  strawberry/src/layout/components/header/LogoutButton.tsx
Labels: :pancakes: fix

#99 랜딩 페이지 스크롤 동작을 추가합니다.
  strawberry/src/core/utils/index.tsx
  strawberry/src/core/utils/scrollTop.ts
  strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx
  strawberry/src/pages/landing/components/landingBanner/LandingBannerScrollButton.tsx
  strawberry/src/pages/landing/hooks/useLandingBanner.tsx
Labels: :pretzel: feat

#98 navigate 시 스크롤 초기화 코드를 추가합니다.
  strawberry/src/core/hooks/useScrollToTop.tsx
  strawberry/src/layout/DefaultLayout.tsx
Labels: :pretzel: feat

#107 드로잉 플레이에 모델 폴더를 추가합니다.
  strawberry/src/pages/drawingPlay/DrawingPlayPage.tsx
  strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayAction.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
  strawberry/src/pages/drawingPlay/models/LineStyle.tsx
  strawberry/src/pages/drawingPlay/models/Point.tsx
  strawberry/src/pages/drawingPlay/models/index.tsx
Labels: :sandwich: refactor

#110 QuizPlay에 서버 API를 연동합니다.
  strawberry/src/pages/quiz/QuizPlayPage.tsx
  strawberry/src/pages/quiz/services/dummy copy 5.ts
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/QuizPlayWrapper.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/HintPopover.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/QuizBackground.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/QuizBoard.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/QuizDescription.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/QuizQuestion.tsx
  strawberry/src/pages/quizPlay/components/quizBoard/QuizSubDescription.tsx
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
  strawberry/src/pages/quizPlay/contexts/dummy copy 5.ts
  strawberry/src/pages/quizPlay/contexts/quizPlayContext.tsx
  strawberry/src/pages/quizPlay/hooks/dummy copy 5.ts
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/queries/useQuizPlayMutation.tsx
  strawberry/src/pages/quizPlay/hooks/queries/useQuizPlayQuery.tsx
  strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx
  strawberry/src/pages/quizPlay/hooks/useQuizPlayData.tsx
  strawberry/src/pages/quizPlay/hooks/useQuizPlayDispatch.tsx
  strawberry/src/pages/quizPlay/hooks/useQuizPlayState.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#117 빌드 시 이미지 경로와 폰트 문제를 해결합니다.
  strawberry/src/core/design_system/buttons/EventButton.tsx
  strawberry/src/core/design_system/reset.css
  strawberry/src/layout/components/footer/Footer.tsx
  strawberry/src/layout/components/header/HeaderLogo.tsx
Labels: :pancakes: fix

#120 퀴즈 랜딩 페이지의 참가 버튼에 게임 페이지 경로를 연결합니다.
  strawberry/src/data/entities/QuizLanding.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
Labels: :pretzel: feat

#123 드로잉 게임 시작 시에 가이드 모달을 보이게 합니다.
  strawberry/src/pages/drawingPlay/components/ProgressBar.tsx
  strawberry/src/pages/drawingPlay/components/drawingOnboarding/DrawingOnboarding.tsx
  strawberry/src/pages/drawingPlay/components/guide/DrawingGuideModal.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideContent.tsx
  strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingOnboarding.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
Labels: :pretzel: feat

#129 공유하기 버튼 기능을 구현합니다.
  strawberry/src/data/entities/DrawingShared.tsx
  strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/components/guide/DrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/components/guide/DrawingPractice.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideCarousel.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideCarouselWrapper.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPractice.tsx
Labels: :pretzel: feat

#131 공통 Carousel을 만듭니다.
  strawberry/src/pages/common/components/carousel/Carousel.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideCarousel.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideCarouselWrapper.tsx
Labels: :sandwich: refactor

#138 드로잉 게임에 게임 정보 API를 연동합니다.
  strawberry/src/core/design_system/reset.css
  strawberry/src/data/entities/DrawingFinish.tsx
  strawberry/src/data/entities/DrawingPlay.tsx
  strawberry/src/data/entities/DrawingResult.tsx
  strawberry/src/data/queries/drawing/useDrawingFinishQuery.tsx
  strawberry/src/data/queries/drawing/useDrawingPlayMutation.tsx
  strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/components/drawingGame/DrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/components/drawingResult/DrawingResult.tsx
  strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingOnboarding.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPlayPage.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingResult.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayAction.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
Labels: :pretzel: feat

#137 신차 소개 페이지의 캐러셀을 구현합니다.
  strawberry/src/assets/images/newCar/arrow_left_default.svg
  strawberry/src/assets/images/newCar/arrow_left_disabled.svg
  strawberry/src/assets/images/newCar/arrow_right_default.svg
  strawberry/src/assets/images/newCar/arrow_right_disabled.svg
  strawberry/src/assets/images/newCar/hybrid_1.svg
  strawberry/src/assets/images/newCar/hybrid_2.svg
  strawberry/src/assets/images/newCar/hybrid_3.svg
  strawberry/src/assets/images/newCar/hybrid_4.svg
  strawberry/src/pages/login/hooks/useNewCarCarousel.tsx
  strawberry/src/pages/newCar/components/newCarCarousel/NewCarCarousel.tsx
Labels: :pretzel: feat

#132 토스트 기능을 추가합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
Labels: :pretzel: feat

#141 토스트를 추가합니다.
  strawberry/src/pages/common/components/toast/Toast.tsx
  strawberry/src/pages/common/hooks/useToast.tsx
Labels: :pancakes: fix

#145 신차 소개페이지 컴포넌트를 만듭니다.
  strawberry/src/core/design_system/styles/Wrapper.tsx
  strawberry/src/pages/common/components/buttons/scrollButton/ScrollButton.tsx
  strawberry/src/pages/common/components/carousel/Carousel.tsx
  strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx
  strawberry/src/pages/newCar/components/FoundationButton.tsx
  strawberry/src/pages/newCar/components/NewCarPage.tsx
  strawberry/src/pages/newCar/components/banner/Background1.svg
  strawberry/src/pages/newCar/components/banner/Background2.svg
  strawberry/src/pages/newCar/components/banner/BannerSantafe.svg
  strawberry/src/pages/newCar/components/banner/NewCarBanner.tsx
  strawberry/src/pages/newCar/components/design/Close.svg
  strawberry/src/pages/newCar/components/design/DesignBackground.svg
  strawberry/src/pages/newCar/components/design/DesignDetailButton.svg
  strawberry/src/pages/newCar/components/design/DetailCarousel.tsx
  strawberry/src/pages/newCar/components/design/ExteriorCalligraphy.tsx
  strawberry/src/pages/newCar/components/design/ExteriorDetailBackground.svg
  strawberry/src/pages/newCar/components/design/NewCarDesign.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesignDetail.tsx
  strawberry/src/pages/newCar/components/design/NewCarExterior.tsx
  strawberry/src/pages/newCar/components/design/NewCarInterior.tsx
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_01.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_02.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_03-1.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_03-2.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_04-1.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_04-2.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_04-3.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_04-4.svg
  strawberry/src/pages/newCar/components/design/Property 1=exterior_front_04-5.svg
  strawberry/src/pages/newCar/components/design/calligraphy_black.svg
  strawberry/src/pages/newCar/components/design/calligraphy_blackInk_whiteMatte.svg
  strawberry/src/pages/newCar/components/design/calligraphy_blackInk_whitePearl.svg
  strawberry/src/pages/newCar/components/design/calligraphy_black_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_blacking_black.svg
  strawberry/src/pages/newCar/components/design/calligraphy_blue.svg
  strawberry/src/pages/newCar/components/design/calligraphy_blue_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_brown.svg
  strawberry/src/pages/newCar/components/design/calligraphy_brown_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_cyber.svg
  strawberry/src/pages/newCar/components/design/calligraphy_cyber_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_gray.svg
  strawberry/src/pages/newCar/components/design/calligraphy_gray_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_green.svg
  strawberry/src/pages/newCar/components/design/calligraphy_green_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_orange.svg
  strawberry/src/pages/newCar/components/design/calligraphy_orange_color.svg
  strawberry/src/pages/newCar/components/design/calligraphy_whitePearl.svg
  strawberry/src/pages/newCar/components/design/calligraphy_whitePearl_color.svg
  strawberry/src/pages/newCar/components/part/NewCarParts.tsx
  strawberry/src/pages/newCar/components/part/Part.tsx
  strawberry/src/pages/newCar/components/part/part1.svg
  strawberry/src/pages/newCar/components/part/part2.svg
  strawberry/src/pages/newCar/components/part/part3.svg
  strawberry/src/pages/newCar/components/part/part4.svg
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#144 신차 소개 페이지의 Driving 배너를 구현합니다.
  strawberry/src/assets/images/newCar/driving_banner.svg
  strawberry/src/pages/newCar/components/drivingBanner/DrivingBanner.tsx
Labels: :pretzel: feat

#146 신차 소개 페이지의 인승에 따른 이미지 뷰어 컴포넌트를 구현합니다.
  strawberry/src/assets/images/newCar/space_5.svg
  strawberry/src/assets/images/newCar/space_6.svg
  strawberry/src/assets/images/newCar/space_7.svg
  strawberry/src/pages/newCar/components/newCarSeats/NewCarSeats.tsx
Labels: :pretzel: feat

#148 신차소개 페이지의 SpaceBanner를 구현합니다.
  strawberry/src/assets/images/newCar/space_banner.svg
  strawberry/src/pages/newCar/components/spaceBanner/SpaceBanner.tsx
Labels: :pretzel: feat

#153 드로잉 게임 progressbar 로직을 수정합니다.
  strawberry/src/pages/drawingPlay/components/drawingOnboarding/DrawingOnboarding.tsx
Labels: :pancakes: fix

#151 퀴즈 플레이 시 엔터로 답안을 제출하고, 오답 모달을 닫고 인풋에 포커스 되도록 합니다.
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
Labels: :pretzel: feat

#156 신차 소개 페이지의 버튼을 포함하는 bottom 컴포넌트를 구현합니다.
  strawberry/src/pages/newCar/components/newCarBottom/NewCarBottom.tsx
Labels: :pretzel: feat

#157 랜딩페이지의 스크롤 버튼 로직을 수정합니다.
  strawberry/src/pages/landing/hooks/useLandingBanner.tsx
Labels: :pancakes: fix

#161 신차 소개 컴포넌트들을 정리하고 페이지를 만듭니다.
  strawberry/src/assets/images/newCar/technology_1.svg
  strawberry/src/assets/images/newCar/technology_2.svg
  strawberry/src/assets/images/newCar/technology_3.svg
  strawberry/src/assets/images/newCar/technology_4.svg
  strawberry/src/assets/images/newCar/technology_5.svg
  strawberry/src/assets/images/newCar/technology_6.svg
  strawberry/src/assets/images/newCar/technology_7.svg
  strawberry/src/pages/newCar/components/NewCarCarousel.tsx
  strawberry/src/pages/newCar/components/NewCarPage.tsx
  strawberry/src/pages/newCar/components/driving/DrivingBanner.tsx
  strawberry/src/pages/newCar/components/driving/DrivingCarousel.tsx
  strawberry/src/pages/newCar/components/driving/NewCarDriving.tsx
  strawberry/src/pages/newCar/components/dummy copy 5.ts
  strawberry/src/pages/newCar/components/gallery/NewCarGallery.tsx
  strawberry/src/pages/newCar/components/space/NewCarSpace.tsx
  strawberry/src/pages/newCar/components/space/SpaceBanner.tsx
  strawberry/src/pages/newCar/components/space/SpaceCarousel.tsx
  strawberry/src/pages/newCar/components/space/SpaceSeats.tsx
  strawberry/src/pages/newCar/models/NewCarCarouselData.tsx
Labels: :pretzel: feat

#167 신차 소개 페이지를 리팩토링합니다.
  strawberry/public/assets/images/newCar/gallery_exterior.webp
  strawberry/public/assets/images/newCar/gallery_interior.webp
  strawberry/public/assets/images/newCar/newcar_banner_background.webp
  strawberry/public/assets/images/newCar/newcar_banner_car.webp
  strawberry/public/assets/images/newCar/parts1.webp
  strawberry/public/assets/images/newCar/parts2.webp
  strawberry/public/assets/images/newCar/parts3.webp
  strawberry/public/assets/images/newCar/parts4.webp
  strawberry/src/core/design_system/ImageEnum.ts
  strawberry/src/pages/newCar/components/NewCarCarousel.tsx
  strawberry/src/pages/newCar/components/NewCarPage.tsx
  strawberry/src/pages/newCar/components/banner/NewCarBanner.tsx
  strawberry/src/pages/newCar/components/bottom/NewCarBottom.tsx
  strawberry/src/pages/newCar/components/design/DesignBanner.tsx
  strawberry/src/pages/newCar/components/design/DetailCarousel.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesign.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesignDetail.tsx
  strawberry/src/pages/newCar/components/driving/DrivingCarousel.tsx
  strawberry/src/pages/newCar/components/gallery/NewCarGallery.tsx
  strawberry/src/pages/newCar/components/part/CarPart.tsx
  strawberry/src/pages/newCar/components/part/NewCarParts.tsx
  strawberry/src/pages/newCar/components/space/SpaceBanner.tsx
  strawberry/src/pages/newCar/components/space/SpaceCarousel.tsx
  strawberry/src/pages/newCar/components/space/SpaceSeats.tsx
  strawberry/src/pages/newCar/models/NewCarCarouselData.tsx
  strawberry/src/pages/newCar/models/NewCarCarouselItem.tsx
  strawberry/src/pages/newCar/models/Part.tsx
Labels: :baguette_bread: rename, :sandwich: refactor

#171 신차소개 페이지 CONTEXT API를 추가합니다
  strawberry/src/pages/newCar/NewCarPage.tsx
  strawberry/src/pages/newCar/components/NewCarPage.tsx
  strawberry/src/pages/newCar/components/NewCarPageWrapper.tsx
  strawberry/src/pages/newCar/contexts/NewCarContext.tsx
  strawberry/src/pages/newCar/contexts/dummy copy 5.ts
  strawberry/src/pages/newCar/hooks/dummy copy 5.ts
  strawberry/src/pages/newCar/models/NewCarAction.tsx
  strawberry/src/pages/newCar/models/NewCarState.tsx
  strawberry/src/pages/newCar/models/NewCarTypes.tsx
  strawberry/src/pages/newCar/models/index.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#178 드로잉 결과 페이지의 디테일 사항을 추가합니다.
  strawberry/public/assets/icons/retry_disabled.svg
  strawberry/src/core/design_system/ImageEnum.ts
  strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx
  strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx
  strawberry/src/data/queries/expectation/useExpectationMutation.tsx
  strawberry/src/pages/common/hooks/useToast.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingInput.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
Labels: :pretzel: feat

#177 OneButtonModal에 Enter로 close할 수 있는 기능을 추가합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/pages/common/components/modal/OneButtonModal.tsx
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
  strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx
Labels: :pretzel: feat

#179 퀴즈 이벤트 진입 시 이벤트 기간이 아닐 때의 경우를 처리합니다.
  strawberry/src/data/queries/quiz/useQuizPlayQuery.tsx
Labels: :pretzel: feat

#181 드로잉 게임의 디테일을 추가합니다.
  strawberry/src/pages/drawingPlay/components/drawingGame/DrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
Labels: :pretzel: feat

#183 모달에 디테일을 추가합니다.
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/hooks/useModal.tsx
Labels: :pretzel: feat

#189 랜딩페이지 배너의 사이즈를 조절합니다.
  strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx
Labels: :pancakes: fix

#191 퀴즈 플레이에서 입력 box를 hightlight하는 기능을 추가합니다.
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
Labels: :pretzel: feat

#187 PublicRouter를 구현합니다.
  strawberry/src/router/ProtectedRoute.tsx
  strawberry/src/router/PublicRoute.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#193 퀴즈 플레이 시 card를 클릭하면 hightlight 해제되는 현상을 해결합니다.
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
Labels: :pancakes: fix

#196 공유하기 리다이렉트 페이지를 추가합니다.
  strawberry/src/pages/shared/SharedRedirectedPage.tsx
Labels: :pancakes: fix

#199 누락된 drawingPlay의 service 로직을 추가합니다.
  strawberry/src/pages/drawingPlay/services/calculateAverageDistance.ts
  strawberry/src/pages/drawingPlay/services/extractInterpolatedPoints.ts
  strawberry/src/pages/drawingPlay/services/interpolatePoints.ts
Labels: :pancakes: fix

#201 신차소개에서 사용하는 context custom hook을 만듭니다.
  strawberry/src/pages/newCar/contexts/NewCarContext.tsx
  strawberry/src/pages/newCar/hooks/useNewCarDispatch.tsx
  strawberry/src/pages/newCar/hooks/useNewCarState.tsx
Labels: :pretzel: feat

#205 라디오버튼을 만듭니다.
  strawberry/src/pages/newCar/components/FoundationButton.tsx
  strawberry/src/pages/newCar/components/FoundationRadioButton.tsx
  strawberry/src/pages/newCar/components/design/ExteriorCalligraphy.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesignDetail.tsx
  strawberry/src/pages/newCar/models/Calligraphy.tsx
Labels: :pretzel: feat

#203 드로잉 결과 페이지의 gif를 추가합니다.
  strawberry/generateImageEnum.cjs
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
Labels: :pretzel: feat

#209 Network에 Custom Error를 추가합니다.
  strawberry/src/App.tsx
  strawberry/src/data/config/BaseError.tsx
  strawberry/src/data/config/BaseResponse.tsx
  strawberry/src/data/config/RequestConfig.tsx
  strawberry/src/data/config/buildURL.tsx
  strawberry/src/data/config/customError.tsx
  strawberry/src/data/config/handleError.tsx
  strawberry/src/data/config/handleQueryError.tsx
  strawberry/src/data/config/makeHeader.tsx
  strawberry/src/data/config/network.tsx
  strawberry/src/data/config/request.tsx
  strawberry/src/data/config/response.tsx
  strawberry/src/data/config/url.tsx
  strawberry/src/data/config/useFetch.tsx
  strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx
Labels: :pretzel: feat

#206 드로잉 시 커서 모양을 연필로 바꿉니다.
  strawberry/public/assets/icons/pencil.svg
  strawberry/public/assets/images/drawing/celebration.gif
  strawberry/src/core/design_system/ImageEnum.ts
  strawberry/src/pages/drawingPlay/components/drawingGame/DrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/components/drawingGame/DrawingGame.tsx
Labels: :pretzel: feat

#207 subEventId에 대한 처리를 추가합니다.
  strawberry/src/data/entities/DrawingLanding.tsx
  strawberry/src/data/queries/drawing/useDrawingFinishQuery.tsx
  strawberry/src/data/queries/drawing/useDrawingPlayMutation.tsx
  strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx
  strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx
  strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingPlayPage.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#212 404페이지를 추가합니다.
  strawberry/src/pages/error/NotFound.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#222 DrawingFinish 컴포넌트에서 남은 기회에 따른 아이콘 기반의 정보를 표시합니다.
  strawberry/public/assets/icons/event_badge_bonus.svg
  strawberry/public/assets/icons/event_badge_bonus_disabled.svg
  strawberry/public/assets/icons/event_badge_normal.svg
  strawberry/public/assets/icons/event_badge_normal_disabled.svg
  strawberry/src/core/design_system/ImageEnum.ts
  strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/ChanceIcons.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
Labels: :pretzel: feat

#219 선착순 퀴즈 제출 시 pending 상태에서의 모달을 추가합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/components/modal/ProgressModal.tsx
  strawberry/src/pages/common/components/progress/SubmitProgress.tsx
  strawberry/src/pages/common/hooks/useSubmitProgress.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
Labels: :pretzel: feat

#217 랜딩페이지에서 퀴즈 remainTime이 0일 때를 처리합니다.
  strawberry/src/pages/landing/components/landingEvent/CountdownTimer.tsx
Labels: :pancakes: fix

#215 로그인하지 않았을 때의 드로잉 랜딩 페이지를 처리합니다.
  strawberry/src/data/queries/eventUser/useEventUserInfoQuery.tsx
  strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx
  strawberry/src/pages/drawingLanding/components/drawingRank/MyDrawingScore.tsx
  strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx
Labels: :pretzel: feat

#223 로그인 후 원래 있던 페이지로 돌아가게 처리합니다.
  strawberry/src/pages/login/hooks/useHandleLoginRedirect.tsx
Labels: :pretzel: feat

#225 공유하기 url path를 수정합니다.
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
Labels: :pancakes: fix

#228 퀴즈 랜딩 페이지의 오늘의 문제, 이벤트 참여 버튼 디테일을 추가합니다.
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizEventEnd.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizOpen.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizOpenStep.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizOpenStep.tsx
Labels: :pretzel: feat

#227 퀴즈 플레이 input 이외의 element 클릭 시 hightlight를 해제합니다.
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
Labels: :pretzel: feat

#234 신차 소개 페이지의 하단 부분을 완성합니다.
  strawberry/src/pages/newCar/components/NewCarCarousel.tsx
  strawberry/src/pages/newCar/components/driving/DrivingCarousel.tsx
  strawberry/src/pages/newCar/components/gallery/NewCarGallery.tsx
  strawberry/src/pages/newCar/components/space/SpaceBanner.tsx
  strawberry/src/pages/newCar/components/space/SpaceCarousel.tsx
  strawberry/src/pages/newCar/components/space/SpaceSeats.tsx
  strawberry/src/pages/newCar/hooks/useGallery.tsx
  strawberry/src/pages/newCar/models/NewCarCarouselItem.tsx
  strawberry/src/pages/newCar/models/NewCarTypes.tsx
  strawberry/src/pages/newCar/models/index.tsx
Labels: :pretzel: feat

#235 이벤트에 처음 참가하는 유저가 정상적으로 드로잉게임을 진행할 수 있도록 합니다.
  strawberry/src/data/queries/drawing/useDrawingRankQuery.tsx
  strawberry/src/data/queries/eventUser/useEventUserInfoQuery.tsx
  strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx
  strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingChance.tsx
  strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx
  strawberry/src/pages/drawingLanding/hooks/useDrawingLandingData.tsx
Labels: :pancakes: fix

#236 퀴즈 플레이 시 중복 참여자 체크 로직을 추가합니다.
  strawberry/src/data/entities/QuizResult.tsx
  strawberry/src/data/queries/quiz/useQuizPlayMutation.tsx
  strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx
Labels: :pretzel: feat

#237 랜딩 페이지 배너에 신차 소개 배너를 추가합니다.
  strawberry/src/pages/landing/LandingPage.tsx
  strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx
Labels: :pretzel: feat

#238 중복 회원가입 시 로직을 처리합니다.
  strawberry/src/data/queries/user/useLoginCallbackQuery.tsx
  strawberry/src/pages/login/hooks/useDuplicatedSignUpModal.tsx
Labels: :pretzel: feat

#241 퀴즈 랜딩 페이지에서 모든 이벤트의 기간이 끝났을 때를 처리합니다.
  strawberry/src/pages/common/components/modal/OneButtonModal.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizOpenStep.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
Labels: :pretzel: feat

#243 누락된 useQuizBanner를 index에 추가합니다.
  strawberry/src/pages/quizLanding/hooks/index.tsx
Labels: :pancakes: fix

#251 리액트 쿼리의 focus 전환 시 패치 로직을 수정합니다.
  strawberry/src/App.tsx
  strawberry/src/data/queries/expectation/useExpectationListQuery.tsx
  strawberry/src/data/queries/expectation/useExpectationPageQuery.tsx
Labels: :pancakes: fix

#252 싼타페 보러가기 버튼에 nowrap 속성을 추가합니다.
  strawberry/src/layout/components/header/CarIntroButton.tsx
Labels: :pancakes: fix

#254 이벤트 기간이 맞지만 아니라는 모달이 뜨는 현상을 해결합니다.
  strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
Labels: :pancakes: fix

#256 로그인 시 게임 화면에 돌아가야 한다면 대신 랜딩으로 돌아가게 합니다.
  strawberry/src/router/ProtectedRoute.tsx
Labels: :pancakes: fix

#258 드로잉 랜딩 페이지에서 보너스 게임만 있을 때 기회가 제대로 조회되지 않는 현상을 해결합니다.
  strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx
  strawberry/src/pages/drawingLanding/hooks/useDrawingChance.tsx
Labels: :pancakes: fix

#260 기대평 제출 시 중복 제출 되는 현상을 해결합니다.
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
  strawberry/src/pages/quizPlay/contexts/quizPlayContext.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
Labels: :pancakes: fix

#261 문자열 submit 시에 blank로만 이루어진 경우를 해결합니다.
  strawberry/src/core/utils/checkOnlyBlank.ts
  strawberry/src/core/utils/index.tsx
  strawberry/src/pages/expectation/components/ExpectationInput.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
  strawberry/src/pages/expectation/hooks/useLengthValidation.tsx
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
Labels: :pancakes: fix

#269 신차 소개에 사용되는 이미지를 수정합니다.
  strawberry/public/assets/icons/Close.svg
  strawberry/public/assets/icons/arrow_backward_ios.svg
  strawberry/public/assets/icons/arrow_forward_ios.svg
  strawberry/public/assets/icons/designDetail.svg
  strawberry/public/assets/images/newCar/exterior_black.webp
  strawberry/public/assets/images/newCar/exterior_blackInk_black.webp
  strawberry/public/assets/images/newCar/exterior_blackInk_whiteMatte.webp
  strawberry/public/assets/images/newCar/exterior_blackInk_whitePearl.webp
  strawberry/public/assets/images/newCar/exterior_black_color.webp
  strawberry/public/assets/images/newCar/exterior_blue.webp
  strawberry/public/assets/images/newCar/exterior_blue_color.webp
  strawberry/public/assets/images/newCar/exterior_brown.webp
  strawberry/public/assets/images/newCar/exterior_brown_color.webp
  strawberry/public/assets/images/newCar/exterior_cyber.webp
  strawberry/public/assets/images/newCar/exterior_cyber_color.webp
  strawberry/public/assets/images/newCar/exterior_gray.webp
  strawberry/public/assets/images/newCar/exterior_gray_color.webp
  strawberry/public/assets/images/newCar/exterior_green.webp
  strawberry/public/assets/images/newCar/exterior_green_color.webp
  strawberry/public/assets/images/newCar/exterior_orange.webp
  strawberry/public/assets/images/newCar/exterior_orange_color.webp
  strawberry/public/assets/images/newCar/exterior_whiteMatte_color.webp
  strawberry/public/assets/images/newCar/exterior_whitePearl.webp
  strawberry/public/assets/images/newCar/exterior_whitePearl_color.webp
  strawberry/public/assets/images/newCar/interior_beige.webp
  strawberry/public/assets/images/newCar/interior_beige_color.webp
  strawberry/public/assets/images/newCar/interior_black.webp
  strawberry/public/assets/images/newCar/interior_blackInk_color.webp
  strawberry/public/assets/images/newCar/interior_black_color.webp
  strawberry/public/assets/images/newCar/interior_blackink.webp
  strawberry/public/assets/images/newCar/interior_brown.webp
  strawberry/public/assets/images/newCar/interior_brown_color.webp
  strawberry/public/assets/images/newCar/interior_fakeBlack_color.webp
  strawberry/public/assets/images/newCar/interior_gray_color.webp
  strawberry/public/assets/images/newCar/interior_realBlack_color.webp
  strawberry/src/core/design_system/ImageEnum.ts
Labels: :pretzel: feat

#266 퀴즈 랜딩 페이지에서 타이머에 따른 버튼 활성화 로직을 추가합니다.
  strawberry/src/core/utils/convertSeconds.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
  strawberry/src/pages/quizLanding/components/quizBanner/QuizBannerTimer.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
  strawberry/src/pages/quizLanding/models/Timer.tsx
Labels: :pretzel: feat

#270 신차 소개 페이지 중 Design 파트에 기능을 구현합니다.
  strawberry/src/pages/newCar/contexts/NewCarContext.tsx
  strawberry/src/pages/newCar/hooks/useCalligraphy.ts
  strawberry/src/pages/newCar/hooks/useDesignDetail.ts
  strawberry/src/pages/newCar/hooks/useDesignDetailCarousel.ts
  strawberry/src/pages/newCar/hooks/useDesignTitle.ts
  strawberry/src/pages/newCar/hooks/useExteriorCalligraphy.ts
  strawberry/src/pages/newCar/hooks/useExteriorDesignDetail.tsx
  strawberry/src/pages/newCar/hooks/useInteriorCalligraphy.ts
  strawberry/src/pages/newCar/hooks/useInteriorDesignDetail.ts
  strawberry/src/pages/newCar/models/Calligraphy.tsx
  strawberry/src/pages/newCar/models/DesginTitle.tsx
  strawberry/src/pages/newCar/models/DesignDetail.tsx
  strawberry/src/pages/newCar/models/NewCarAction.tsx
  strawberry/src/pages/newCar/models/NewCarState.tsx
  strawberry/src/pages/newCar/models/NewCarTypes.tsx
  strawberry/src/pages/newCar/models/index.tsx
  strawberry/src/pages/newCar/services/designDetailCarouselService.ts
  strawberry/src/pages/newCar/services/designTitleService.ts
  strawberry/src/pages/newCar/services/exteriorCalligraphyService.ts
  strawberry/src/pages/newCar/services/exteriorDesignDetailService.ts
  strawberry/src/pages/newCar/services/getPositionStyle.tsx
Labels: :pretzel: feat

#272 신차소개 페이지 중 Design Part의 컴포넌트를 수정합니다.
  strawberry/src/pages/common/components/carousel/Carousel.tsx
  strawberry/src/pages/drawingPlay/components/guide/GuideCarouselWrapper.tsx
  strawberry/src/pages/newCar/components/design/DesignCalligraphy.tsx
  strawberry/src/pages/newCar/components/design/DesignDetail.tsx
  strawberry/src/pages/newCar/components/design/DesignDetailCarousel.tsx
  strawberry/src/pages/newCar/components/design/DesignDetailTitle.tsx
  strawberry/src/pages/newCar/components/design/DetailCarousel.tsx
  strawberry/src/pages/newCar/components/design/ExteriorCalligraphy.tsx
  strawberry/src/pages/newCar/components/design/ExteriorDesignDetail.tsx
  strawberry/src/pages/newCar/components/design/ExteriorTitle.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesign.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesignDetail.tsx
  strawberry/src/pages/newCar/components/design/NewCarExterior.tsx
  strawberry/src/pages/newCar/components/design/NewCarInterior.tsx
Labels: :pretzel: feat

#277 퀴즈 페이지 진입 시 대기열을 추가합니다.
  strawberry/src/core/contexts/globalContext.tsx
  strawberry/src/data/entities/QuizWaiting.tsx
  strawberry/src/data/entities/QuizWaitingRemaining.tsx
  strawberry/src/data/queries/quiz/useQuizPlayMutation.tsx
  strawberry/src/data/queries/quiz/useQuizPlayQuery.tsx
  strawberry/src/data/queries/quiz/useQuizWaitingMutation.tsx
  strawberry/src/data/queries/quiz/useQuizWaitingQuery.tsx
  strawberry/src/pages/common/components/modal/Modal.tsx
  strawberry/src/pages/common/components/modal/WaitingModal.tsx
  strawberry/src/pages/common/components/progress/SubmitProgress.tsx
  strawberry/src/pages/common/hooks/useSubmitProgress.tsx
  strawberry/src/pages/quizLanding/contexts/QuizLandingContext.tsx
  strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
  strawberry/src/pages/quizLanding/models/QuizLandingAction.tsx
  strawberry/src/pages/quizLanding/models/QuizLandingState.tsx
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/useQuizPlayData.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#280 충돌 해결 중 지워진 코드를 추가합니다.
  strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
Labels: :pancakes: fix

#281 퀴즈 플레이 화면에서 헤더 퀴즈 탭으로 이동 시의 문제를 해결합니다.
  strawberry/src/layout/components/header/HeaderMenuButtons.tsx
Labels: :pancakes: fix

#284 반영되지 않은 코드를 머지합니다.
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
Labels: :pancakes: fix

#286 반영되지 않은 사항을 추가합니다.
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
  strawberry/src/pages/quizPlay/QuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
  strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx
Labels: :pretzel: feat

#287 기대평 페이지에 작성된 글이 없을 시에 보여줄 컴포넌트를 추가합니다.
  strawberry/src/pages/expectation/ExpectationPage.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationPage.tsx
  strawberry/src/pages/expectation/hooks/useExpectationData.tsx
Labels: :pretzel: feat

#290 보너스 기회 획득 후 사용하지 않았을 경우에도 overlay 처리를 추가합니다.
  strawberry/src/pages/drawingLanding/hooks/useDrawingBadges.tsx
Labels: :pancakes: fix

#292 드로잉 게임의 기대평 작성 시 enter를 통해 제출할 수 있도록 추가합니다.
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingInput.tsx
Labels: :pretzel: feat

#294 feat: Lazy Loading, IntersectionObserver를 추가합니다.
  strawberry/src/core/design_system/styles/Wrapper.tsx
  strawberry/src/pages/newCar/NewCarPage.tsx
  strawberry/src/pages/newCar/RenderOnViewportEntry.tsx
  strawberry/src/pages/newCar/useFirstViewportEntry.ts
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#295 신차소개 페이지에 애니메이션을 적용합니다.
  strawberry/package-lock.json
  strawberry/package.json
  strawberry/src/core/design_system/reset.css
  strawberry/src/core/design_system/styles/AnimText.tsx
  strawberry/src/pages/login/hooks/useNewCarCarousel.tsx
  strawberry/src/pages/newCar/NewCarPageWrapper.tsx
  strawberry/src/pages/newCar/components/AnimationSection.tsx
  strawberry/src/pages/newCar/components/NewCarCarousel.tsx
  strawberry/src/pages/newCar/components/banner/NewCarBanner.tsx
  strawberry/src/pages/newCar/components/bottom/NewCarBottom.tsx
  strawberry/src/pages/newCar/components/design/DesignBanner.tsx
  strawberry/src/pages/newCar/components/design/DesignCalligraphy.tsx
  strawberry/src/pages/newCar/components/design/DesignDetail.tsx
  strawberry/src/pages/newCar/components/design/DesignDetailCarousel.tsx
  strawberry/src/pages/newCar/components/design/ExteriorDesignDetail.tsx
  strawberry/src/pages/newCar/components/design/ExteriorTitle.tsx
  strawberry/src/pages/newCar/components/design/NewCarDesign.tsx
  strawberry/src/pages/newCar/components/design/NewCarExterior.tsx
  strawberry/src/pages/newCar/components/design/NewCarInterior.tsx
  strawberry/src/pages/newCar/components/driving/DrivingBanner.tsx
  strawberry/src/pages/newCar/components/driving/DrivingCarousel.tsx
  strawberry/src/pages/newCar/components/gallery/NewCarGallery.tsx
  strawberry/src/pages/newCar/components/part/CarPart.tsx
  strawberry/src/pages/newCar/components/part/NewCarParts.tsx
  strawberry/src/pages/newCar/components/space/SpaceBanner.tsx
  strawberry/src/pages/newCar/components/space/SpaceCarousel.tsx
  strawberry/src/pages/newCar/components/space/SpaceSeats.tsx
  strawberry/src/pages/newCar/models/index.tsx
Labels: :pretzel: feat

#298 드로잉 게임에 변경사항을 추가합니다.
  strawberry/index.html
  strawberry/public/hyundai_logo.svg
  strawberry/src/core/design_system/reset.css
  strawberry/src/data/config/logging.tsx
  strawberry/src/layout/DefaultLayout.tsx
  strawberry/src/layout/HeaderLayout.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
  strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingInput.tsx
  strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
  strawberry/src/pages/drawingPlay/hooks/useDrawingResult.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayAction.tsx
  strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
  strawberry/src/pages/expectation/ExpectationPage.tsx
  strawberry/src/pages/expectation/components/ExpectationInput.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
  strawberry/src/pages/expectation/hooks/logics/useExpectationPage.tsx
  strawberry/src/pages/newCar/NewCarPage.tsx
  strawberry/src/pages/newCar/components/banner/NewCarBanner.tsx
  strawberry/src/pages/newCar/hooks/useExteriorDesignDetail.tsx
  strawberry/src/pages/quizLanding/components/quizOpen/QuizOpen.tsx
  strawberry/src/router/router.tsx
Labels: :pretzel: feat

#299 푸터를 제작합니다.
  .github/workflows/node.js.yml
  strawberry/.gitignore
  strawberry/public/assets/fonts/Hyundai_Sans_Head_KR_Regular.ttf
  strawberry/public/assets/images/footer/facebook.svg
  strawberry/public/assets/images/footer/instagram.svg
  strawberry/public/assets/images/footer/item1.svg
  strawberry/public/assets/images/footer/item2.svg
  strawberry/public/assets/images/footer/item3.svg
  strawberry/public/assets/images/footer/logo.svg
  strawberry/public/assets/images/footer/x.svg
  strawberry/public/assets/images/footer/youtube.svg
  strawberry/src/assets/fonts/Hyundai_Sans_Head_KR_Light.ttf
  strawberry/src/assets/fonts/Hyundai_Sans_Head_KR_Medium.ttf
  strawberry/src/assets/fonts/Hyundai_Sans_Head_KR_Regular.ttf
  strawberry/src/core/design_system/ImageEnum.ts
  strawberry/src/layout/components/footer/Footer.tsx
  strawberry/src/layout/components/footer/paths.ts
Labels: :pretzel: feat

#301 폰트를 변경합니다.
  strawberry/public/assets/fonts/Hyundai_Sans_Head_KR_Medium.ttf
  strawberry/src/core/design_system/reset.css
  strawberry/src/pages/introduce/components/dummy copy 5.ts
  strawberry/src/pages/introduce/contexts/dummy copy 5.ts
  strawberry/src/pages/introduce/hooks/dummy copy 5.ts
  strawberry/src/pages/introduce/services/dummy copy 5.ts
Labels: :pretzel: feat

#303 발견한 버그를 수정합니다.
  strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
Labels: :pancakes: fix

#305 공유 링크 리다이렉트 주소를 변경합니다.
  strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
Labels: :pancakes: fix
